// Контент тренажёра. Уровни: 0 = A0 (старт), 1 = A1, 2 = A2, 3 = B1, 4 = B2, 5 = C1, 6 = C2.

const LEVELS = [
  { code: 'A0', name: 'Старт' },
  { code: 'A1', name: 'Начальный' },
  { code: 'A2', name: 'Базовый' },
  { code: 'B1', name: 'Средний' },
  { code: 'B2', name: 'Выше среднего' },
  { code: 'C1', name: 'Продвинутый' },
  { code: 'C2', name: 'В совершенстве' },
];

const SKILLS = {
  vocab:   { name: 'Слова' },
  grammar: { name: 'Грамматика' },
  reading: { name: 'Чтение' },
};

// Темы: ключ -> навык, название, уровень
const TOPICS = {
  'v:food':     { skill: 'vocab', ru: 'Еда', level: 0 },
  'v:animals':  { skill: 'vocab', ru: 'Животные', level: 0 },
  'v:colors':   { skill: 'vocab', ru: 'Цвета', level: 0 },
  'v:numbers':  { skill: 'vocab', ru: 'Числа', level: 0 },
  'v:people':   { skill: 'vocab', ru: 'Люди', level: 0 },
  'v:home':     { skill: 'vocab', ru: 'Дом', level: 1 },
  'v:clothes':  { skill: 'vocab', ru: 'Одежда', level: 1 },
  'v:body':     { skill: 'vocab', ru: 'Тело', level: 1 },
  'v:travel':   { skill: 'vocab', ru: 'Транспорт', level: 1 },
  'v:nature':   { skill: 'vocab', ru: 'Природа и погода', level: 1 },
  'v:city':     { skill: 'vocab', ru: 'Город', level: 1 },
  'v:jobs':     { skill: 'vocab', ru: 'Профессии', level: 2 },
  'v:things':   { skill: 'vocab', ru: 'Вещи', level: 2 },
  'v:verbs':    { skill: 'vocab', ru: 'Действия', level: 2 },
  'v:feelings': { skill: 'vocab', ru: 'Чувства', level: 2 },
  'v:health':   { skill: 'vocab', ru: 'Здоровье', level: 3 },
  'v:tech':     { skill: 'vocab', ru: 'Техника и наука', level: 3 },
  'v:events':   { skill: 'vocab', ru: 'События и досуг', level: 3 },
  'v:tools':    { skill: 'vocab', ru: 'Инструменты', level: 4 },
  'v:wildlife': { skill: 'vocab', ru: 'Дикая природа', level: 4 },
  'v:emotions': { skill: 'vocab', ru: 'Оттенки эмоций', level: 4 },
  'v:business': { skill: 'vocab', ru: 'Работа и бизнес', level: 5 },
  'v:idioms':   { skill: 'vocab', ru: 'Идиомы', level: 5 },
  'v:rare':     { skill: 'vocab', ru: 'Книжная лексика', level: 6 },
  'v:idioms2':  { skill: 'vocab', ru: 'Сложные идиомы', level: 6 },

  'g:be':          { skill: 'grammar', ru: 'am / is / are', level: 0 },
  'g:articles':    { skill: 'grammar', ru: 'Артикли a / an', level: 0 },
  'g:plural':      { skill: 'grammar', ru: 'Множественное число', level: 0 },
  'g:pronouns':    { skill: 'grammar', ru: 'Местоимения he / she / they', level: 0 },
  'g:haveHas':     { skill: 'grammar', ru: 'have / has', level: 1 },
  'g:present':     { skill: 'grammar', ru: 'Present Simple', level: 1 },
  'g:negatives':   { skill: 'grammar', ru: 'Отрицания don’t / doesn’t', level: 1 },
  'g:questions':   { skill: 'grammar', ru: 'Вопросы do / does', level: 1 },
  'g:thereIs':     { skill: 'grammar', ru: 'There is / there are', level: 1 },
  'g:can':         { skill: 'grammar', ru: 'Глагол can', level: 1 },
  'g:prepositions':{ skill: 'grammar', ru: 'Предлоги in / on / under', level: 1 },
  'g:continuous':  { skill: 'grammar', ru: 'Present Continuous', level: 2 },
  'g:past':        { skill: 'grammar', ru: 'Past Simple', level: 2 },
  'g:future':      { skill: 'grammar', ru: 'Будущее с will', level: 2 },
  'g:comparatives':{ skill: 'grammar', ru: 'Сравнение bigger / the best', level: 2 },
  'g:perfect':     { skill: 'grammar', ru: 'Present Perfect', level: 3 },
  'g:conditional': { skill: 'grammar', ru: 'Условия if … will', level: 3 },
  'g:passive':     { skill: 'grammar', ru: 'Пассивный залог', level: 3 },
  'g:modals':      { skill: 'grammar', ru: 'should / must / have to', level: 3 },
  'g:conditional2':{ skill: 'grammar', ru: 'Условия 2 и 3 типа', level: 4 },
  'g:reported':    { skill: 'grammar', ru: 'Косвенная речь', level: 4 },
  'g:pastPerfect': { skill: 'grammar', ru: 'Past Perfect и Perfect Continuous', level: 4 },
  'g:gerund':      { skill: 'grammar', ru: 'Герундий и инфинитив', level: 4 },
  'g:inversion':   { skill: 'grammar', ru: 'Инверсия', level: 5 },
  'g:wish':        { skill: 'grammar', ru: 'I wish / If only', level: 5 },
  'g:causative':   { skill: 'grammar', ru: 'have something done, безличный пассив', level: 5 },
  'g:mixedCond':   { skill: 'grammar', ru: 'Смешанные условия', level: 5 },
  'g:modalsPast':  { skill: 'grammar', ru: 'Модальные глаголы о прошлом', level: 6 },
  'g:subjunctive': { skill: 'grammar', ru: 'Сослагательное наклонение', level: 6 },
  'g:cleft':       { skill: 'grammar', ru: 'Эмфатические конструкции', level: 6 },

  'r:phrases': { skill: 'reading', ru: 'Короткие фразы', level: 0 },
  'r:scenes':  { skill: 'reading', ru: 'Фразы о действиях', level: 1 },
  'r:texts1':  { skill: 'reading', ru: 'Короткие тексты', level: 1 },
  'r:texts2':  { skill: 'reading', ru: 'Истории', level: 2 },
  'r:texts3':  { skill: 'reading', ru: 'Статьи и письма', level: 3 },
  'r:texts4':  { skill: 'reading', ru: 'Новости и исследования', level: 4 },
  'r:texts5':  { skill: 'reading', ru: 'Аналитические статьи', level: 5 },
  'r:texts6':  { skill: 'reading', ru: 'Эссе', level: 6 },
};

// [английский, русский, эмодзи, тема]
const WORDS = [
  ['apple','яблоко','🍎','food'], ['banana','банан','🍌','food'], ['bread','хлеб','🍞','food'],
  ['milk','молоко','🥛','food'], ['egg','яйцо','🥚','food'], ['cheese','сыр','🧀','food'],
  ['coffee','кофе','☕','food'], ['pizza','пицца','🍕','food'], ['cake','торт','🍰','food'],
  ['carrot','морковь','🥕','food'], ['grapes','виноград','🍇','food'], ['water','вода','💧','food'],

  ['cat','кошка','🐱','animals'], ['dog','собака','🐶','animals'], ['bird','птица','🐦','animals'],
  ['horse','лошадь','🐴','animals'], ['cow','корова','🐮','animals'], ['pig','свинья','🐷','animals'],
  ['mouse','мышь','🐭','animals'], ['rabbit','кролик','🐰','animals'], ['bear','медведь','🐻','animals'],
  ['lion','лев','🦁','animals'], ['fish','рыба','🐟','animals'], ['frog','лягушка','🐸','animals'],

  ['red','красный','🟥','colors'], ['blue','синий','🟦','colors'], ['green','зелёный','🟩','colors'],
  ['yellow','жёлтый','🟨','colors'], ['black','чёрный','⬛','colors'], ['white','белый','⬜','colors'],
  ['orange','оранжевый','🟧','colors'], ['purple','фиолетовый','🟪','colors'], ['brown','коричневый','🟫','colors'],

  ['one','один','1️⃣','numbers'], ['two','два','2️⃣','numbers'], ['three','три','3️⃣','numbers'],
  ['four','четыре','4️⃣','numbers'], ['five','пять','5️⃣','numbers'], ['six','шесть','6️⃣','numbers'],
  ['seven','семь','7️⃣','numbers'], ['eight','восемь','8️⃣','numbers'], ['nine','девять','9️⃣','numbers'],
  ['ten','десять','🔟','numbers'],

  ['man','мужчина','👨','people'], ['woman','женщина','👩','people'], ['boy','мальчик','👦','people'],
  ['girl','девочка','👧','people'], ['baby','малыш','👶','people'], ['family','семья','👪','people'],
  ['grandmother','бабушка','👵','people'], ['grandfather','дедушка','👴','people'],

  ['house','дом','🏠','home'], ['door','дверь','🚪','home'], ['bed','кровать','🛏️','home'],
  ['chair','стул','🪑','home'], ['window','окно','🪟','home'], ['key','ключ','🔑','home'],
  ['phone','телефон','📱','home'], ['book','книга','📖','home'], ['clock','часы','🕰️','home'],
  ['sofa','диван','🛋️','home'], ['TV','телевизор','📺','home'],

  ['T-shirt','футболка','👕','clothes'], ['dress','платье','👗','clothes'], ['shoes','ботинки','👞','clothes'],
  ['hat','шляпа','🎩','clothes'], ['glasses','очки','👓','clothes'], ['coat','пальто','🧥','clothes'],
  ['socks','носки','🧦','clothes'], ['bag','сумка','👜','clothes'], ['jeans','джинсы','👖','clothes'],
  ['gloves','перчатки','🧤','clothes'],

  ['eye','глаз','👁️','body'], ['ear','ухо','👂','body'], ['nose','нос','👃','body'],
  ['hand','рука','✋','body'], ['foot','ступня','🦶','body'], ['mouth','рот','👄','body'],
  ['heart','сердце','❤️','body'], ['tooth','зуб','🦷','body'], ['leg','нога','🦵','body'],

  ['car','машина','🚗','travel'], ['bus','автобус','🚌','travel'], ['train','поезд','🚆','travel'],
  ['plane','самолёт','✈️','travel'], ['bike','велосипед','🚲','travel'], ['ship','корабль','🚢','travel'],
  ['taxi','такси','🚕','travel'], ['ticket','билет','🎫','travel'], ['map','карта','🗺️','travel'],
  ['suitcase','чемодан','🧳','travel'],

  ['sun','солнце','☀️','nature'], ['rain','дождь','🌧️','nature'], ['snow','снег','❄️','nature'],
  ['tree','дерево','🌳','nature'], ['flower','цветок','🌸','nature'], ['moon','луна','🌙','nature'],
  ['star','звезда','⭐','nature'], ['mountain','гора','⛰️','nature'], ['sea','море','🌊','nature'],
  ['cloud','облако','☁️','nature'],

  ['hospital','больница','🏥','city'], ['school','школа','🏫','city'], ['bank','банк','🏦','city'],
  ['shop','магазин','🏪','city'], ['hotel','отель','🏨','city'], ['park','парк','🏞️','city'],
  ['bridge','мост','🌉','city'], ['money','деньги','💵','city'],

  ['doctor','врач','🧑‍⚕️','jobs'], ['teacher','учитель','🧑‍🏫','jobs'], ['cook','повар','🧑‍🍳','jobs'],
  ['police officer','полицейский','👮','jobs'], ['farmer','фермер','🧑‍🌾','jobs'], ['firefighter','пожарный','🧑‍🚒','jobs'],
  ['pilot','пилот','🧑‍✈️','jobs'], ['artist','художник','🧑‍🎨','jobs'],

  ['computer','компьютер','💻','things'], ['letter','письмо','✉️','things'], ['umbrella','зонт','☂️','things'],
  ['gift','подарок','🎁','things'], ['camera','фотоаппарат','📷','things'], ['scissors','ножницы','✂️','things'],
  ['pen','ручка','🖊️','things'], ['newspaper','газета','📰','things'], ['calendar','календарь','📅','things'],
  ['candle','свеча','🕯️','things'],

  ['run','бегать','🏃','verbs'], ['swim','плавать','🏊','verbs'], ['sleep','спать','😴','verbs'],
  ['dance','танцевать','💃','verbs'], ['sing','петь','🎤','verbs'], ['write','писать','✍️','verbs'],
  ['cry','плакать','😢','verbs'], ['laugh','смеяться','😂','verbs'], ['think','думать','🤔','verbs'],
  ['climb','лазать','🧗','verbs'],

  ['happy','счастливый','😊','feelings'], ['sad','грустный','😞','feelings'], ['angry','злой','😠','feelings'],
  ['tired','уставший','😫','feelings'], ['hot','жарко','🥵','feelings'], ['cold','холодно','🥶','feelings'],
  ['sick','больной','🤒','feelings'], ['surprised','удивлённый','😲','feelings'],

  ['medicine','лекарство','💊','health'], ['injection','укол','💉','health'], ['plaster','пластырь','🩹','health'],
  ['thermometer','градусник','🌡️','health'], ['ambulance','скорая помощь','🚑','health'], ['stethoscope','стетоскоп','🩺','health'],
  ['crutch','костыль','🩼','health'], ['bone','кость','🦴','health'],

  ['battery','батарейка','🔋','tech'], ['plug','вилка (розетка)','🔌','tech'], ['satellite','спутник','🛰️','tech'],
  ['magnet','магнит','🧲','tech'], ['robot','робот','🤖','tech'], ['keyboard','клавиатура','⌨️','tech'],
  ['microscope','микроскоп','🔬','tech'], ['rocket','ракета','🚀','tech'], ['telescope','телескоп','🔭','tech'],

  ['wedding','свадьба','💒','events'], ['birthday','день рождения','🎂','events'], ['concert','концерт','🎻','events'],
  ['exhibition','выставка','🖼️','events'], ['fireworks','фейерверк','🎆','events'], ['trophy','кубок','🏆','events'],
  ['tent','палатка','⛺','events'], ['ticket office','касса','🎟️','events'],

  ['hammer','молоток','🔨','tools'], ['saw','пила','🪚','tools'], ['screwdriver','отвёртка','🪛','tools'],
  ['wrench','гаечный ключ','🔧','tools'], ['ladder','стремянка','🪜','tools'], ['bucket','ведро','🪣','tools'],
  ['broom','метла','🧹','tools'], ['sponge','губка','🧽','tools'], ['padlock','навесной замок','🔒','tools'],
  ['chain','цепь','⛓️','tools'],

  ['squirrel','белка','🐿️','wildlife'], ['hedgehog','ёж','🦔','wildlife'], ['owl','сова','🦉','wildlife'],
  ['bat','летучая мышь','🦇','wildlife'], ['beaver','бобр','🦫','wildlife'], ['snail','улитка','🐌','wildlife'],
  ['crab','краб','🦀','wildlife'], ['octopus','осьминог','🐙','wildlife'], ['parrot','попугай','🦜','wildlife'],
  ['volcano','вулкан','🌋','wildlife'],

  ['exhausted','измотанный','😩','emotions'], ['furious','взбешённый','🤬','emotions'], ['astonished','поражённый','😱','emotions'],
  ['embarrassed','смущённый','😳','emotions'], ['disgusted','испытывающий отвращение','🤢','emotions'], ['relieved','с облегчением','😌','emotions'],
  ['anxious','встревоженный','😰','emotions'], ['bored','скучающий','🥱','emotions'], ['confused','растерянный','😕','emotions'],
  ['suspicious','подозрительный','🤨','emotions'],

  ['deadline','крайний срок','⏰','business'], ['negotiation','переговоры','🤝','business'], ['investment','инвестиция','📈','business'],
  ['promotion','повышение','🎖️','business'], ['salary','зарплата','💰','business'], ['CV','резюме','📄','business'],
  ['colleague','коллега','👥','business'], ['interview','собеседование','🎙️','business'], ['headquarters','штаб-квартира','🏢','business'],
  ['bankruptcy','банкротство','📉','business'],

  ['piece of cake','проще простого','🍰👌','idioms'], ['break the ice','растопить лёд в общении','🧊🔨','idioms'],
  ['under the weather','неважно себя чувствовать','🤒☁️','idioms'], ['hit the books','засесть за учёбу','📚👊','idioms'],
  ['spill the beans','проболтаться','🫘💬','idioms'], ['once in a blue moon','очень редко','🔵🌙','idioms'],
  ['cost an arm and a leg','стоить целое состояние','💸🦵','idioms'], ['when pigs fly','когда рак на горе свистнет','🐷✈️','idioms'],
  ['let the cat out of the bag','выдать секрет','🐱👜','idioms'], ['the ball is in your court','теперь твой ход','🎾👉','idioms'],

  ['ephemeral','мимолётный','🫧','rare'], ['serendipity','счастливая случайность','🍀','rare'], ['epiphany','озарение','💡','rare'],
  ['nostalgia','ностальгия','📼','rare'], ['mirage','мираж','🏜️','rare'], ['labyrinth','лабиринт','🌀','rare'],
  ['eclipse','затмение','🌒','rare'], ['solitude','уединение','🏝️','rare'], ['wanderlust','тяга к странствиям','🎒','rare'],
  ['resilience','стойкость','🌱','rare'],

  ['a blessing in disguise','нет худа без добра','🎁🎭','idioms2'], ['bite the bullet','стиснуть зубы и сделать','😬💪','idioms2'],
  ['burn the midnight oil','работать до глубокой ночи','🌃💻','idioms2'], ['the elephant in the room','проблема, которую все замалчивают','🐘🛋️','idioms2'],
  ['bark up the wrong tree','искать не там','🐕🌲','idioms2'], ['jump on the bandwagon','примкнуть к модному течению','🎺🚋','idioms2'],
  ['a drop in the ocean','капля в море','💧🌊','idioms2'], ['play devil’s advocate','спорить ради спора','😈⚖️','idioms2'],
  ['cut corners','халтурить, экономя на качестве','✂️📐','idioms2'], ['the tip of the iceberg','верхушка айсберга','🧊🏔️','idioms2'],
].map(([en, ru, e, t]) => ({ en, ru, e, t }));

// Грамматика. s + o: вставь слово (первый вариант — верный). w: собери фразу из слов.
const GRAMMAR = {
  be: [
    { s: 'I ___ a student.', o: ['am', 'is', 'are'], ru: 'Я студент.' },
    { s: 'She ___ from Italy.', o: ['is', 'am', 'are'], ru: 'Она из Италии.' },
    { s: 'We ___ friends.', o: ['are', 'is', 'am'], ru: 'Мы друзья.' },
    { w: 'My name is Anna', end: '.', ru: 'Меня зовут Анна.' },
    { w: 'They are at home', end: '.', ru: 'Они дома.' },
  ],
  articles: [
    { s: 'This is ___ apple.', o: ['an', 'a'], ru: 'Это яблоко.' },
    { s: 'I have ___ dog.', o: ['a', 'an'], ru: 'У меня есть собака.' },
    { s: 'She is ___ doctor.', o: ['a', 'an'], ru: 'Она врач.' },
    { w: 'It is an orange', end: '.', ru: 'Это апельсин.' },
    { w: 'He has a car', end: '.', ru: 'У него есть машина.' },
  ],
  plural: [
    { s: 'one cat — two ___', o: ['cats', 'cat', 'cates'], ru: 'одна кошка — две кошки' },
    { s: 'one box — three ___', o: ['boxes', 'boxs', 'box'], ru: 'одна коробка — три коробки' },
    { s: 'one man — two ___', o: ['men', 'mans', 'man'], ru: 'один мужчина — двое мужчин' },
    { w: 'I have two dogs', end: '.', ru: 'У меня две собаки.' },
    { w: 'These are my books', end: '.', ru: 'Это мои книги.' },
  ],
  pronouns: [
    { e: '👦', s: '___ is my brother.', o: ['He', 'She', 'It'], ru: 'Он мой брат.' },
    { e: '👩', s: '___ is a teacher.', o: ['She', 'He', 'They'], ru: 'Она учитель.' },
    { e: '👪', s: '___ are my family.', o: ['They', 'He', 'She'], ru: 'Они моя семья.' },
    { w: 'We are happy', end: '.', ru: 'Мы счастливы.' },
    { w: 'It is my cat', end: '.', ru: 'Это мой кот.' },
  ],
  haveHas: [
    { s: 'She ___ a big house.', o: ['has', 'have', 'is'], ru: 'У неё большой дом.' },
    { s: 'I ___ two sisters.', o: ['have', 'has', 'am'], ru: 'У меня две сестры.' },
    { s: 'My brother ___ a new car.', o: ['has', 'have', 'are'], ru: 'У моего брата новая машина.' },
    { w: 'We have a dog', end: '.', ru: 'У нас есть собака.' },
    { w: 'He has blue eyes', end: '.', ru: 'У него голубые глаза.' },
  ],
  present: [
    { s: 'He ___ coffee every morning.', o: ['drinks', 'drink', 'drinking'], ru: 'Он пьёт кофе каждое утро.' },
    { s: 'They ___ in London.', o: ['live', 'lives', 'living'], ru: 'Они живут в Лондоне.' },
    { s: 'My mom ___ in a bank.', o: ['works', 'work', 'working'], ru: 'Моя мама работает в банке.' },
    { w: 'I get up at seven', end: '.', ru: 'Я встаю в семь.' },
    { w: 'She reads books every day', end: '.', ru: 'Она читает книги каждый день.' },
  ],
  negatives: [
    { s: 'I ___ like milk.', o: ['don’t', 'doesn’t', 'not'], ru: 'Я не люблю молоко.' },
    { s: 'He ___ eat meat.', o: ['doesn’t', 'don’t', 'isn’t'], ru: 'Он не ест мясо.' },
    { s: 'We ___ tired.', o: ['aren’t', 'don’t', 'doesn’t'], ru: 'Мы не устали.' },
    { w: 'She doesn’t speak French', end: '.', ru: 'Она не говорит по-французски.' },
    { w: 'I am not hungry', end: '.', ru: 'Я не голоден.' },
  ],
  questions: [
    { s: '___ you like tea?', o: ['Do', 'Does', 'Are'], ru: 'Ты любишь чай?' },
    { s: '___ she work here?', o: ['Does', 'Do', 'Is'], ru: 'Она работает здесь?' },
    { s: '___ they at home?', o: ['Are', 'Do', 'Is'], ru: 'Они дома?' },
    { w: 'Where do you live', end: '?', ru: 'Где ты живёшь?' },
    { w: 'What is your name', end: '?', ru: 'Как тебя зовут?' },
  ],
  thereIs: [
    { s: 'There ___ a cat on the bed.', o: ['is', 'are', 'am'], ru: 'На кровати кошка.' },
    { s: 'There ___ three apples on the table.', o: ['are', 'is', 'be'], ru: 'На столе три яблока.' },
    { s: '___ there a bank near here?', o: ['Is', 'Are', 'Do'], ru: 'Здесь рядом есть банк?' },
    { w: 'There is a park near my house', end: '.', ru: 'Рядом с моим домом есть парк.' },
    { w: 'There are two windows in the room', end: '.', ru: 'В комнате два окна.' },
  ],
  can: [
    { s: 'I can ___.', o: ['swim', 'swims', 'swimming'], ru: 'Я умею плавать.' },
    { s: 'She ___ speak English.', o: ['can', 'cans', 'is can'], ru: 'Она умеет говорить по-английски.' },
    { s: '___ you help me?', o: ['Can', 'Do', 'Are'], ru: 'Ты можешь мне помочь?' },
    { w: 'He can play the guitar', end: '.', ru: 'Он умеет играть на гитаре.' },
    { w: 'I can’t drive a car', end: '.', ru: 'Я не умею водить машину.' },
  ],
  prepositions: [
    { s: 'The cat is ___ the box.', o: ['in', 'on', 'under'], ru: 'Кошка в коробке.' },
    { s: 'The book is ___ the table.', o: ['on', 'in', 'under'], ru: 'Книга на столе.' },
    { s: 'The dog is ___ the bed.', o: ['under', 'on', 'in'], ru: 'Собака под кроватью.' },
    { w: 'My keys are in my bag', end: '.', ru: 'Мои ключи в сумке.' },
    { w: 'The phone is on the sofa', end: '.', ru: 'Телефон на диване.' },
  ],
  continuous: [
    { s: 'Look! It ___ raining.', o: ['is', 'are', 'does'], ru: 'Смотри! Идёт дождь.' },
    { s: 'I am ___ a book now.', o: ['reading', 'read', 'reads'], ru: 'Я сейчас читаю книгу.' },
    { s: 'They ___ playing football.', o: ['are', 'is', 'do'], ru: 'Они играют в футбол.' },
    { w: 'She is cooking dinner now', end: '.', ru: 'Она сейчас готовит ужин.' },
    { w: 'What are you doing', end: '?', ru: 'Что ты делаешь?' },
  ],
  past: [
    { s: 'Yesterday I ___ to the park.', o: ['went', 'go', 'goes'], ru: 'Вчера я ходил в парк.' },
    { s: 'She ___ a cake last Sunday.', o: ['made', 'make', 'makes'], ru: 'Она испекла торт в прошлое воскресенье.' },
    { s: 'We ___ TV last night.', o: ['watched', 'watch', 'watching'], ru: 'Вчера вечером мы смотрели телевизор.' },
    { w: 'I saw a good film yesterday', end: '.', ru: 'Вчера я посмотрел хороший фильм.' },
    { w: 'Did you sleep well', end: '?', ru: 'Ты хорошо спал?' },
  ],
  future: [
    { s: 'Tomorrow I ___ visit my mom.', o: ['will', 'am', 'did'], ru: 'Завтра я навещу маму.' },
    { s: 'It ___ be cold tomorrow.', o: ['will', 'is', 'was'], ru: 'Завтра будет холодно.' },
    { s: 'I think she ___ like this gift.', o: ['will', 'is', 'does'], ru: 'Думаю, ей понравится этот подарок.' },
    { w: 'We will go to the sea next summer', end: '.', ru: 'Следующим летом мы поедем на море.' },
    { w: 'I will call you later', end: '.', ru: 'Я позвоню тебе позже.' },
  ],
  comparatives: [
    { s: 'An elephant is ___ than a dog.', o: ['bigger', 'big', 'biggest'], ru: 'Слон больше собаки.' },
    { s: 'Summer is ___ than winter.', o: ['hotter', 'hoter', 'more hot'], ru: 'Летом жарче, чем зимой.' },
    { s: 'This is the ___ day of my life!', o: ['best', 'better', 'good'], ru: 'Это лучший день в моей жизни!' },
    { w: 'My sister is younger than me', end: '.', ru: 'Моя сестра младше меня.' },
    { w: 'This book is more interesting than that one', end: '.', ru: 'Эта книга интереснее той.' },
  ],
  perfect: [
    { s: 'I have never ___ sushi.', o: ['eaten', 'ate', 'eat'], ru: 'Я никогда не ел суши.' },
    { s: 'She ___ already finished her work.', o: ['has', 'have', 'is'], ru: 'Она уже закончила работу.' },
    { s: 'Have you ever ___ to London?', o: ['been', 'was', 'go'], ru: 'Ты когда-нибудь был в Лондоне?' },
    { w: 'We have lived here for five years', end: '.', ru: 'Мы живём здесь пять лет.' },
    { w: 'Has he called you yet', end: '?', ru: 'Он тебе уже звонил?' },
  ],
  conditional: [
    { s: 'If it rains, we ___ stay at home.', o: ['will', 'would', 'are'], ru: 'Если пойдёт дождь, мы останемся дома.' },
    { s: 'If you ___ hard, you will pass the exam.', o: ['study', 'will study', 'studied'], ru: 'Если будешь усердно учиться, сдашь экзамен.' },
    { s: 'I will call you if I ___ time.', o: ['have', 'will have', 'had'], ru: 'Я позвоню, если будет время.' },
    { w: 'If you are tired you should rest', end: '.', ru: 'Если ты устал, тебе стоит отдохнуть.' },
    { w: 'She will be angry if we are late', end: '.', ru: 'Она рассердится, если мы опоздаем.' },
  ],
  passive: [
    { s: 'This house ___ built in 1990.', o: ['was', 'is', 'did'], ru: 'Этот дом построили в 1990 году.' },
    { s: 'English is ___ all over the world.', o: ['spoken', 'speak', 'spoke'], ru: 'На английском говорят по всему миру.' },
    { s: 'The letters ___ sent yesterday.', o: ['were', 'was', 'are'], ru: 'Письма отправили вчера.' },
    { w: 'The car is washed every week', end: '.', ru: 'Машину моют каждую неделю.' },
    { w: 'This film was made in France', end: '.', ru: 'Этот фильм сняли во Франции.' },
  ],
  modals: [
    { s: 'You look tired. You ___ go to bed.', o: ['should', 'must not', 'can’t'], ru: 'Ты выглядишь уставшим. Тебе стоит лечь спать.' },
    { s: 'You ___ smoke here. It’s forbidden.', o: ['mustn’t', 'don’t have to', 'should'], ru: 'Здесь нельзя курить. Это запрещено.' },
    { s: 'Tomorrow is Sunday, so I ___ get up early.', o: ['don’t have to', 'mustn’t', 'must'], ru: 'Завтра воскресенье, так что мне не нужно рано вставать.' },
    { w: 'I have to work on Saturday', end: '.', ru: 'Мне приходится работать в субботу.' },
    { w: 'You should see a doctor', end: '.', ru: 'Тебе стоит сходить к врачу.' },
  ],
  conditional2: [
    { s: 'If I ___ rich, I would travel the world.', o: ['were', 'am', 'will be'], ru: 'Если бы я был богат, я бы путешествовал по миру.' },
    { s: 'If she had studied, she ___ passed the exam.', o: ['would have', 'will have', 'would'], ru: 'Если бы она занималась, она бы сдала экзамен.' },
    { s: 'I would call him if I ___ his number.', o: ['knew', 'know', 'had known'], ru: 'Я бы позвонил ему, если бы знал его номер.' },
    { w: 'If I had known I would have come', end: '.', ru: 'Если бы я знал, я бы пришёл.' },
    { w: 'What would you do if you won the lottery', end: '?', ru: 'Что бы ты сделал, если бы выиграл в лотерею?' },
  ],
  reported: [
    { s: 'She said that she ___ tired.', o: ['was', 'is', 'will be'], ru: 'Она сказала, что устала.' },
    { s: 'He asked me where I ___.', o: ['lived', 'do live', 'did live'], ru: 'Он спросил, где я живу.' },
    { s: 'They told us they ___ the film before.', o: ['had seen', 'have seen', 'see'], ru: 'Они сказали, что уже видели этот фильм.' },
    { w: 'She asked me if I could help her', end: '.', ru: 'Она спросила, не могу ли я ей помочь.' },
    { w: 'He told me not to worry', end: '.', ru: 'Он сказал мне не волноваться.' },
  ],
  pastPerfect: [
    { s: 'When we arrived, the train ___ already left.', o: ['had', 'has', 'was'], ru: 'Когда мы приехали, поезд уже ушёл.' },
    { s: 'I have ___ waiting for an hour!', o: ['been', 'be', 'being'], ru: 'Я жду уже целый час!' },
    { s: 'She was tired because she ___ working all day.', o: ['had been', 'has been', 'is'], ru: 'Она устала, потому что работала весь день.' },
    { w: 'How long have you been learning English', end: '?', ru: 'Как давно ты учишь английский?' },
    { w: 'By the time I woke up everyone had left', end: '.', ru: 'К тому времени, как я проснулся, все уже ушли.' },
  ],
  gerund: [
    { s: 'I enjoy ___ in the rain.', o: ['walking', 'to walk', 'walk'], ru: 'Я люблю гулять под дождём.' },
    { s: 'She decided ___ a new job.', o: ['to find', 'finding', 'find'], ru: 'Она решила найти новую работу.' },
    { s: 'Would you mind ___ the window?', o: ['opening', 'to open', 'open'], ru: 'Не могли бы вы открыть окно?' },
    { w: 'I am looking forward to seeing you', end: '.', ru: 'С нетерпением жду встречи с тобой.' },
    { w: 'He stopped smoking last year', end: '.', ru: 'Он бросил курить в прошлом году.' },
  ],
  inversion: [
    { s: 'Never ___ I seen such a beautiful place.', o: ['have', 'did', 'was'], ru: 'Никогда я не видел такого красивого места.' },
    { s: 'Not only ___ she sing, but she also dances.', o: ['does', 'is', 'do'], ru: 'Она не только поёт, но и танцует.' },
    { s: 'Hardly ___ we arrived when it started to rain.', o: ['had', 'have', 'did'], ru: 'Едва мы приехали, как пошёл дождь.' },
    { w: 'Rarely do we see such talent', end: '.', ru: 'Редко встретишь такой талант.' },
    { w: 'Under no circumstances should you open this door', end: '.', ru: 'Ни при каких обстоятельствах не открывайте эту дверь.' },
  ],
  wish: [
    { s: 'I wish I ___ more free time.', o: ['had', 'have', 'will have'], ru: 'Жаль, что у меня мало свободного времени.' },
    { s: 'If only I ___ listened to you!', o: ['had', 'have', 'would'], ru: 'Если бы только я тебя послушал!' },
    { s: 'I wish you ___ stop interrupting me.', o: ['would', 'will', 'did'], ru: 'Хоть бы ты перестал меня перебивать.' },
    { w: 'I wish I had studied harder', end: '.', ru: 'Жаль, что я не учился усерднее.' },
    { w: 'If only it would stop raining', end: '.', ru: 'Хоть бы дождь прекратился.' },
  ],
  causative: [
    { s: 'I had my hair ___ yesterday.', o: ['cut', 'cutting', 'to cut'], ru: 'Вчера я подстригся (в парикмахерской).' },
    { s: 'It ___ said that he is a millionaire.', o: ['is', 'has', 'does'], ru: 'Говорят, что он миллионер.' },
    { s: 'She is believed ___ left the country.', o: ['to have', 'having', 'to'], ru: 'Считается, что она уехала из страны.' },
    { w: 'We are having our kitchen renovated', end: '.', ru: 'Нам ремонтируют кухню.' },
    { w: 'He is said to be very rich', end: '.', ru: 'Говорят, он очень богат.' },
  ],
  mixedCond: [
    { s: 'If I had taken that job, I ___ in Paris now.', o: ['would be living', 'will live', 'would have lived'], ru: 'Если бы я тогда согласился на ту работу, сейчас бы жил в Париже.' },
    { s: 'If he weren’t so lazy, he ___ the exam last week.', o: ['would have passed', 'would pass', 'will pass'], ru: 'Не будь он таким ленивым, он бы сдал экзамен на прошлой неделе.' },
    { s: 'If I ___ harder at school, I would have a better job now.', o: ['had studied', 'studied', 'study'], ru: 'Если бы я лучше учился в школе, сейчас у меня была бы работа получше.' },
    { w: 'If I had saved money I would be rich now', end: '.', ru: 'Если бы я копил деньги, сейчас был бы богат.' },
    { w: 'If she were more careful she would not have crashed', end: '.', ru: 'Будь она осторожнее, она бы не разбилась.' },
  ],
  modalsPast: [
    { s: 'He ___ have forgotten — he is never late.', o: ['must', 'can', 'should'], ru: 'Он, должно быть, забыл — он никогда не опаздывает.' },
    { s: 'You ___ have told me! I would have helped.', o: ['should', 'must', 'can'], ru: 'Тебе следовало мне сказать! Я бы помог.' },
    { s: 'They ___ have seen us — it was too dark.', o: ['can’t', 'mustn’t', 'shouldn’t'], ru: 'Они не могли нас видеть — было слишком темно.' },
    { w: 'You needn’t have brought anything', end: '.', ru: 'Не нужно было ничего приносить.' },
    { w: 'She might have missed the train', end: '.', ru: 'Возможно, она опоздала на поезд.' },
  ],
  subjunctive: [
    { s: 'I suggest that he ___ a doctor.', o: ['see', 'sees', 'will see'], ru: 'Я предлагаю, чтобы он сходил к врачу.' },
    { s: 'It is essential that she ___ on time.', o: ['be', 'is', 'will be'], ru: 'Крайне важно, чтобы она пришла вовремя.' },
    { s: 'It’s high time we ___ home.', o: ['went', 'go', 'will go'], ru: 'Нам давно пора домой.' },
    { w: 'I would rather you stayed here', end: '.', ru: 'Я бы предпочёл, чтобы ты остался здесь.' },
    { w: 'The doctor recommended that she rest', end: '.', ru: 'Врач порекомендовал ей отдохнуть.' },
  ],
  cleft: [
    { s: '___ I need is a long holiday.', o: ['What', 'That', 'Which'], ru: 'Что мне нужно — так это долгий отпуск.' },
    { s: 'It was John ___ broke the window.', o: ['who', 'what', 'whom'], ru: 'Именно Джон разбил окно.' },
    { s: 'All I want ___ some peace and quiet.', o: ['is', 'are', 'be'], ru: 'Всё, чего я хочу, — немного тишины и покоя.' },
    { w: 'What surprised me was his honesty', end: '.', ru: 'Меня удивила именно его честность.' },
    { w: 'It was in Paris that we first met', end: '.', ru: 'Именно в Париже мы впервые встретились.' },
  ],
};

// «Правда или нет» для уровня A1: картинка + фраза
const SCENES = [
  { scene: '🏃', s: 'The man is running.', truth: true, ru: 'Мужчина бежит.' },
  { scene: '😴', s: 'He is sleeping.', truth: true, ru: 'Он спит.' },
  { scene: '🌧️', s: 'It is sunny today.', truth: false, ru: 'Сегодня солнечно.' },
  { scene: '❄️', s: 'It is snowing.', truth: true, ru: 'Идёт снег.' },
  { scene: '🍕🍕🍕', s: 'There are three pizzas.', truth: true, ru: 'Здесь три пиццы.' },
  { scene: '🚌', s: 'This is a train.', truth: false, ru: 'Это поезд.' },
  { scene: '🧑‍🍳', s: 'She is a cook.', truth: true, ru: 'Она повар.' },
  { scene: '🥶', s: 'He is cold.', truth: true, ru: 'Ему холодно.' },
  { scene: '🥵', s: 'She is very cold.', truth: false, ru: 'Ей очень холодно.' },
  { scene: '🐶🐱', s: 'There is a dog and a cat.', truth: true, ru: 'Здесь собака и кошка.' },
  { scene: '🐶🐶🐱', s: 'There are two cats and a dog.', truth: false, ru: 'Здесь две кошки и собака.' },
  { scene: '💃', s: 'The woman is swimming.', truth: false, ru: 'Женщина плавает.' },
  { scene: '☕🍰', s: 'I have coffee and cake.', truth: true, ru: 'У меня кофе и торт.' },
  { scene: '😢', s: 'The girl is laughing.', truth: false, ru: 'Девочка смеётся.' },
];

// Тексты: level 1 = A1 … 6 = C2. В вариантах ответа первый — верный.
const TEXTS = [
  { level: 1, title: 'Tom',
    text: 'Hi! My name is Tom. I am 30. I live in London with my wife and two cats. I am a teacher. I like coffee and pizza.',
    q: [
      { q: 'What is Tom’s job?', qr: 'Кем работает Том?', o: ['a teacher', 'a doctor', 'a cook'] },
      { q: 'How many cats does Tom have?', qr: 'Сколько у Тома кошек?', o: ['two', 'one', 'three'] },
      { q: 'Where does Tom live?', qr: 'Где живёт Том?', o: ['in London', 'in Paris', 'in Moscow'] },
    ] },
  { level: 1, title: 'Anna’s day',
    text: 'Anna gets up at 7. She drinks tea and eats bread with cheese. She goes to work by bus. She works in a bank. In the evening she reads a book.',
    q: [
      { q: 'What does Anna drink in the morning?', qr: 'Что Анна пьёт утром?', o: ['tea', 'coffee', 'milk'] },
      { q: 'How does Anna go to work?', qr: 'Как Анна добирается на работу?', o: ['by bus', 'by car', 'by train'] },
      { q: 'Where does Anna work?', qr: 'Где работает Анна?', o: ['in a bank', 'in a shop', 'in a school'] },
    ] },
  { level: 1, title: 'My house',
    text: 'My house is small but nice. There are two rooms and a kitchen. There is a big window in my room. My dog sleeps under my bed.',
    q: [
      { q: 'How many rooms are there?', qr: 'Сколько в доме комнат?', o: ['two', 'three', 'one'] },
      { q: 'Where does the dog sleep?', qr: 'Где спит собака?', o: ['under the bed', 'on the bed', 'in the kitchen'] },
    ] },
  { level: 1, title: 'At the café',
    text: 'Waiter: Hello! What would you like? Mike: A coffee and a cake, please. Waiter: Anything else? Mike: No, thank you. How much is it? Waiter: Five dollars.',
    q: [
      { q: 'What does Mike order?', qr: 'Что заказывает Майк?', o: ['coffee and cake', 'tea and pizza', 'water and bread'] },
      { q: 'How much is it?', qr: 'Сколько это стоит?', o: ['five dollars', 'fifteen dollars', 'fifty dollars'] },
    ] },
  { level: 2, title: 'The weekend',
    text: 'Last weekend I went to the mountains with my friends. On Saturday it was sunny and we walked for five hours. On Sunday it rained, so we stayed in the hotel and played cards. It was a great trip!',
    q: [
      { q: 'Where did they go?', qr: 'Куда они ездили?', o: ['to the mountains', 'to the sea', 'to the city'] },
      { q: 'What was the weather on Sunday?', qr: 'Какая была погода в воскресенье?', o: ['rainy', 'sunny', 'snowy'] },
      { q: 'What did they do on Sunday?', qr: 'Что они делали в воскресенье?', o: ['played cards', 'walked for five hours', 'swam in the sea'] },
    ] },
  { level: 2, title: 'A new job',
    text: 'Kate started a new job last month. She is a designer in a big company. Her office is far from home, so she gets up very early. She is tired, but she is happy because she loves her work.',
    q: [
      { q: 'What is Kate’s job?', qr: 'Кем работает Кейт?', o: ['a designer', 'a driver', 'a nurse'] },
      { q: 'Why does Kate get up early?', qr: 'Почему Кейт рано встаёт?', o: ['her office is far', 'she likes mornings', 'she has a dog'] },
      { q: 'How does Kate feel?', qr: 'Как себя чувствует Кейт?', o: ['tired but happy', 'sad and angry', 'bored'] },
    ] },
  { level: 2, title: 'Travel plans',
    text: 'Next summer Sam will travel to Italy. He will fly to Rome and then take a train to Florence. He wants to see old buildings and eat real Italian pizza. Now he is learning Italian.',
    q: [
      { q: 'Where will Sam fly?', qr: 'Куда полетит Сэм?', o: ['to Rome', 'to Florence', 'to Milan'] },
      { q: 'How will he get to Florence?', qr: 'Как он доберётся до Флоренции?', o: ['by train', 'by bus', 'by car'] },
      { q: 'What is Sam learning now?', qr: 'Что Сэм сейчас учит?', o: ['Italian', 'Spanish', 'French'] },
    ] },
  { level: 2, title: 'Two brothers',
    text: 'My brother and I are very different. He is taller than me, but I am older. He likes sport, and I like books. He gets up early, and I sleep until ten on Sundays.',
    q: [
      { q: 'Who is older?', qr: 'Кто старше?', o: ['I am', 'my brother', 'we are the same age'] },
      { q: 'What does the brother like?', qr: 'Что любит брат?', o: ['sport', 'books', 'music'] },
    ] },
  { level: 3, title: 'Working from home',
    text: 'More and more people work from home these days. They don’t have to travel to the office, so they save time and money. However, some of them feel lonely because they rarely see their colleagues. Experts say it is important to have a routine: get up at the same time, get dressed and take regular breaks.',
    q: [
      { q: 'What is one advantage of working from home?', qr: 'Какой плюс у работы из дома?', o: ['saving time and money', 'meeting colleagues', 'a bigger salary'] },
      { q: 'What problem do some people have?', qr: 'С какой проблемой сталкиваются некоторые люди?', o: ['they feel lonely', 'they get lost', 'they work less'] },
      { q: 'What do experts recommend?', qr: 'Что советуют эксперты?', o: ['having a routine', 'working at night', 'never taking breaks'] },
    ] },
  { level: 3, title: 'A letter to a hotel',
    text: 'Dear Sir or Madam, I stayed at your hotel from 3 to 5 May. The room was clean and the staff were friendly, but the Wi-Fi didn’t work and nobody fixed it. I have already written to the reception twice. I would be grateful if you could return part of the payment. Yours faithfully, Laura Green.',
    q: [
      { q: 'What did Laura like?', qr: 'Что понравилось Лоре?', o: ['the clean room and friendly staff', 'the Wi-Fi', 'the breakfast'] },
      { q: 'What was the problem?', qr: 'В чём была проблема?', o: ['the Wi-Fi didn’t work', 'the room was dirty', 'the staff were rude'] },
      { q: 'What does Laura want?', qr: 'Чего хочет Лора?', o: ['part of her money back', 'a free night', 'a new room'] },
    ] },
  { level: 3, title: 'Sleep',
    text: 'Scientists have found that adults need seven to nine hours of sleep. If you don’t sleep enough, you will find it harder to concentrate and remember new information. Phones and laptops should be switched off an hour before bed, because their light makes the brain think it is still daytime.',
    q: [
      { q: 'How much sleep do adults need?', qr: 'Сколько сна нужно взрослым?', o: ['seven to nine hours', 'five hours', 'ten to twelve hours'] },
      { q: 'What happens if you don’t sleep enough?', qr: 'Что будет, если мало спать?', o: ['it is harder to concentrate', 'you become taller', 'you learn faster'] },
      { q: 'Why should you switch off phones before bed?', qr: 'Почему стоит выключать телефон перед сном?', o: ['their light confuses the brain', 'they are too loud', 'they use a lot of power'] },
    ] },
  { level: 4, title: 'The four-day week',
    text: 'Several companies in Britain recently took part in an experiment: employees worked four days a week instead of five but received the same salary. At the end of the six-month trial, most companies decided to keep the new schedule. Managers reported that productivity had not fallen, while staff said they felt less stressed and had more time for their families. Critics, however, argue that the model would be difficult to introduce in hospitals or schools, where someone has to be present every day.',
    q: [
      { q: 'How long did the trial last?', qr: 'Сколько длился эксперимент?', o: ['six months', 'one year', 'four weeks'] },
      { q: 'What did most companies decide?', qr: 'Что решило большинство компаний?', o: ['to keep the new schedule', 'to return to a five-day week', 'to cut salaries'] },
      { q: 'What do critics say?', qr: 'Что говорят критики?', o: ['it would be hard to use in hospitals and schools', 'productivity fell sharply', 'employees were unhappy'] },
    ] },
  { level: 4, title: 'Too late to learn?',
    text: 'Many adults believe it is too late for them to learn a foreign language. Research suggests otherwise. Although children usually achieve better pronunciation, adults often make faster progress at the beginning, because they can use learning strategies, understand grammar rules and plan their studies. The key factor seems to be regular practice: twenty minutes a day turns out to be more effective than a three-hour lesson once a week.',
    q: [
      { q: 'What do children usually do better?', qr: 'Что у детей обычно получается лучше?', o: ['pronunciation', 'grammar', 'planning'] },
      { q: 'Why do adults progress faster at first?', qr: 'Почему взрослые сначала продвигаются быстрее?', o: ['they can use learning strategies', 'they have more free time', 'they are less tired'] },
      { q: 'What is the most effective approach?', qr: 'Что эффективнее всего?', o: ['short daily practice', 'one long weekly lesson', 'studying only grammar'] },
    ] },
  { level: 5, title: 'The paradox of choice',
    text: 'Common sense tells us that the more options we have, the happier we will be. Yet the psychologist Barry Schwartz argues the opposite. Faced with dozens of almost identical products, shoppers often feel overwhelmed, postpone their decision or leave without buying anything at all. Even when they do choose, they are more likely to regret it, constantly wondering whether one of the alternatives would have been better. Schwartz suggests that deliberately limiting our options, for instance by deciding in advance how long we will spend on a purchase, can leave us more satisfied.',
    q: [
      { q: 'What does Schwartz argue?', qr: 'Что утверждает Шварц?', o: ['more choice can make us less happy', 'more choice always makes us happier', 'shops should raise their prices'] },
      { q: 'What often happens to shoppers?', qr: 'Что часто происходит с покупателями?', o: ['they postpone the decision or give up', 'they buy everything at once', 'they decide very quickly'] },
      { q: 'What does he recommend?', qr: 'Что он советует?', o: ['limiting our options on purpose', 'comparing every single product', 'shopping only online'] },
    ] },
  { level: 5, title: 'Bees on the roof',
    text: 'Rooftop beehives have become surprisingly common in cities such as London and Paris. Supporters claim they help to reverse the decline of bees. However, some ecologists warn that the trend may be doing more harm than good: honeybees compete with wild bees for a limited supply of flowers, and in areas with too many hives, wild species may be pushed out. Rather than installing ever more hives, they argue, cities should plant more flowering trees and leave parts of their parks uncut.',
    q: [
      { q: 'What worries some ecologists?', qr: 'Что беспокоит некоторых экологов?', o: ['honeybees compete with wild bees', 'hives are too expensive', 'rooftops are dangerous for people'] },
      { q: 'What do they suggest instead?', qr: 'Что они предлагают взамен?', o: ['planting more flowers and trees', 'banning bees in cities', 'building larger hives'] },
      { q: 'Where have rooftop hives become common?', qr: 'Где распространились ульи на крышах?', o: ['in cities like London and Paris', 'mainly in villages', 'in desert regions'] },
    ] },
  { level: 6, title: 'In praise of boredom',
    text: 'Boredom has long been regarded as a trivial, even shameful, state — something to be eliminated at the first opportunity, usually by reaching for a phone. Yet a growing body of research suggests that it may serve a purpose. Far from being a mere absence of stimulation, boredom appears to function as a signal that our current activity has ceased to be meaningful, nudging us towards goals we might otherwise neglect. In one series of experiments, participants who had completed deliberately tedious tasks subsequently generated more original ideas than a control group. The danger, researchers caution, lies not in boredom itself but in our reflex to numb it instantly, thereby depriving ourselves of the very discomfort that prompts change.',
    q: [
      { q: 'How has boredom traditionally been viewed?', qr: 'Как традиционно относились к скуке?', o: ['as trivial and something to avoid', 'as a source of wisdom', 'as a serious illness'] },
      { q: 'What did the experiments show?', qr: 'Что показали эксперименты?', o: ['bored participants had more original ideas', 'bored participants performed worse', 'there was no difference at all'] },
      { q: 'What is the real danger, according to researchers?', qr: 'В чём, по мнению исследователей, настоящая опасность?', o: ['escaping boredom immediately', 'feeling bored too often', 'doing creative tasks'] },
    ] },
  { level: 6, title: 'The authenticity trap',
    text: 'Travellers increasingly profess a desire for authentic experiences: eating where the locals eat and avoiding anything that smacks of tourism. The irony is that the very pursuit of authenticity tends to erode it. Once a hidden café is praised in a guidebook, it is swiftly transformed by the crowds that the praise attracts; prices rise, menus are translated and the regulars drift elsewhere. Some sociologists go further, contending that the distinction between authentic and staged culture is itself dubious, since every tradition was, at some point, invented and performed for an audience.',
    q: [
      { q: 'What irony does the author describe?', qr: 'Какую иронию описывает автор?', o: ['searching for authenticity destroys it', 'tourists dislike local food', 'guidebooks are always wrong'] },
      { q: 'What happens to a praised hidden café?', qr: 'Что происходит с расхваленным тайным кафе?', o: ['it changes because of the crowds', 'it closes immediately', 'it becomes cheaper'] },
      { q: 'What do some sociologists argue?', qr: 'Что утверждают некоторые социологи?', o: ['the line between authentic and staged is questionable', 'all traditions are worthless', 'tourists should stay at home'] },
    ] },
];

// Генератор простых фраз «Правда или нет» (A0)
const PHRASE_WORDS = WORDS.filter(w => ['food', 'animals', 'people'].includes(w.t) && !['water', 'grapes', 'milk', 'cheese', 'bread', 'coffee'].includes(w.en));
const thisIs = w => `This is ${/^[aeiou]/.test(w.en) ? 'an' : 'a'} ${w.en}.`;
const COUNTABLE = [['cats', '🐱', 'кошки'], ['dogs', '🐶', 'собаки'], ['apples', '🍎', 'яблока'], ['cars', '🚗', 'машины'], ['books', '📖', 'книги'], ['stars', '⭐', 'звезды'], ['trees', '🌳', 'дерева'], ['birds', '🐦', 'птицы']];
const NUM = ['', 'one', 'two', 'three', 'four'];
